### ISSUE TITLE
Рефакторинг интерфейса

### ISSUE THREAD

**Issue by mensch25** [marilisok/timer-android#18]
Выделить элементы ui в отдельные классы, доработать визуальную составляющую 
#17

**Comment by nechepurenkoN** [comment]
Я в #19 разбил на классы, все вроде работает, правда память течет.
Если тебя код устраивает, можешь сделать merge #19, или внеси изменения в feature-18.

Утечки памяти я исправлю потом (или не исправлю :)), поэтому осталось навести красоту. Мне кажется, что список с историей должен быть снизу. Хотелось бы увидеть более симпатичные стили и progressbar, вроде такого 

![](https://imgur.com/doK8mpi.jpg)
Тысячи извинений за такую большую картинку.
